In [1]:
import pandas as pd
import numpy as np
from textstat.textstat import textstat

In [2]:
data = pd.read_csv('amazon_reviews.txt', delimiter='\t')
data['LABEL'] = data['LABEL'].map({'__label1__': 'fake', '__label2__': 'real'})
data['LABEL_INT'] = data['LABEL'].map({'fake': 1, 'real': 0})
data['VERIFIED_PURCHASE_INT'] = data['VERIFIED_PURCHASE'].map({'Y': 1, 'N': 0})

data

,DOC_ID,LABEL,RATING,VERIFIED_PURCHASE,PRODUCT_CATEGORY,PRODUCT_ID,PRODUCT_TITLE,REVIEW_TITLE,REVIEW_TEXT,LABEL_INT,VERIFIED_PURCHASE_INT
0,1,fake,4,N,PC,B00008NG7N,"Targus PAUK10U Ultra Mini USB Keypad, Black",useful,"When least you think so, this product will sav...",1,0
1,2,fake,4,Y,Wireless,B00LH0Y3NM,Note 3 Battery : Stalion Strength Replacement ...,New era for batteries,Lithium batteries are something new introduced...,1,1
2,3,fake,3,N,Baby,B000I5UZ1Q,"Fisher-Price Papasan Cradle Swing, Starlight",doesn't swing very well.,I purchased this swing for my baby. She is 6 m...,1,0
3,4,fake,4,N,Office Products,B003822IRA,Casio MS-80B Standard Function Desktop Calculator,Great computing!,I was looking for an inexpensive desk calcolat...,1,0
4,5,fake,4,N,Beauty,B00PWSAXAM,Shine Whitening - Zero Peroxide Teeth Whitenin...,Only use twice a week,I only use it twice a week and the results are...,1,0
5,6,fake,3,N,Health & Personal Care,B00686HNUK,Tobacco Pipe Stand - Fold-away Portable - Ligh...,not sure,I'm not sure what this is supposed to be but I...,1,0
6,7,fake,4,N,Toys,B00NUG865W,ESPN 2-Piece Table Tennis,PING PONG TABLE GREAT FOR YOUTHS AND FAMILY,Pleased with ping pong table. 11 year old and ...,1,0
7,8,fake,4,Y,Beauty,B00QUL8VX6,Abundant Health 25% Vitamin C Serum with Vitam...,Great vitamin C serum,Great vitamin C serum... I really like the oil...,1,1
8,9,fake,4,N,Health & Personal Care,B004YHKVCM,PODS Spring Meadow HE Turbo Laundry Detergent ...,wonderful detergent.,I've used tide pods laundry detergent for many...,1,0
9,10,fake,1,N,Health & Personal Care,B00H4IBD0M,"Sheer TEST, Best Testosterone Booster Suppleme...",WARNING: do not waste your money on this,Everybody wants to fall for their promises. Bu...,1,0
10,11,fake,1,N,Health & Personal Care,B00VQNLQL2,#1 Most Potent Male Performance Enhancement Su...,Unfortunately they didn't work for me.,Unfortunately they didn't work for me. They ma...,1,0
11,12,fake,4,N,Kitchen,B00IWOJS9A,"Proctor Silex K2070YA Electric Kettle, 1-Liter",She said that it is easy to use,This kettle is a gift for my daughter. She sai...,1,0
12,13,fake,4,N,Kitchen,B00JEGSZCQ,Stainless Steel Tumbler with Straw- Hot and Co...,Works great,I love this tumbler! Keeps drinks warm or cold...,1,0
13,14,fake,4,N,Health & Personal Care,B000TD0PXU,Now Foods Mood Support With St Johns Wort Veg-...,Just OK,Only giving this 3 stars because it is so chea...,1,0
14,15,fake,4,N,Furniture,B0019QITHK,"Boss Caressoft Medical Stool, black",Color Is Accurate,I bought 2 of these in brown for my island. Th...,1,0
15,16,fake,4,N,Electronics,B004WODP20,Sony MDRZX100 ZX Series Stereo Headphones (Bl...,Price is right!,wonderful headphones had them now for 5 months...,1,0
16,17,fake,4,Y,Camera,B00E56WY18,"Falcon Zero F360 HD DVR Dual Dash Cam, Rear Vi...","Good design, but a recommendation","Video quality if superb, fits just fine, looks...",1,1
17,18,fake,4,N,Sports,B000HE8NK8,Barnett Diablo Slingshot,good enough,"As sling shots go, this is good enough for my ...",1,0
18,19,fake,4,Y,Kitchen,B00FJKEGRY,Cuisavour's Deluxe Spiral Slicer with Japanese...,I just wish that there were guides and manuals...,"just to be fair, i really believe that this is...",1,1
19,20,fake,4,Y,Health & Personal Care,B00KNXIDH6,100 Tablet CleanGuard Nightguard Cleaner,and he was satisfied with this,These tablets are especially helpful if you us...,1,1
20,21,fake,4,N,Home,B00LWRZFAA,Birds Flying Black Tree Branches Wall Sticker ...,best of money value,Looking decent as same shown in photos Thank Y...,1,0
21,22,fake,4,Y,Health & Personal Care,B00B2YGB9M,"Garcinia Cambogia Pure Extract Supplement, 80%...",It's harder to lose weight the older you get,"I find that the older I get, the harder it is ...",1,1
22,23,fake,3,N,Camera,B004TJ6JH6,NEEWER® 160 LED CN-160 Dimmable Ultra High Pow...,So easy to use!!,I have had my camera for about 2 weeks now. Th...,1,0
23,24,fake,2,Y,Health & Personal Care,B00OBDRLVS,NatureWise Garcinia Cambogia Extract (Not Synt...,Stay Away And Don't Buy It,It is highly recommended not to buy this produ...,1,1
24,25,fake,3,N,PC,B002RWJGHM,Thermaltake Power Supply 240-Pin 600 Power Sup...,good supply,"The actual power supply is good, but the cable...",1,0
25,26,fake,4,N,Health & Personal Care,B0018KL0YG,Oregano Oil CERTIFIED ORGANIC- Joy of the Moun...,Did you know? Oregano delivers more antioxidan...,My personal physician recommended it and I bou...,1,0
26,27,fake,4,N,Kitchen,B00004OCO6,OXO Good Grips 6-Piece Measuring Cup Set,Products are great,I love the fact that you can easily read the m...,1,0
27,28,fake,4,Y,Health & Personal Care,B009LO31HK,SVETOL® Green Coffee Bean Extract 50% Acid - ...,One of the better ones,I have bought several products from this selle...,1,1
28,29,fake,4,N,Home,B001L1R3SO,Soft Heat Luxury Micro-Fleece Low-Voltage Elec...,Better than expected,This is an extremely well made electric blanke...,1,0
29,30,fake,4,Y,Kitchen,B00PYF1J24,Cafe Deluxe French Press Coffee Maker & Coffee...,great product for coffee lover that want littl...,great product for coffee lover that want littl...,1,1
...,...,...,...,...,...,...,...,...,...,...,...
20970,20971,real,5,Y,Shoes,B00AW7N4PY,"Timberland Women's Savin Hill Mid Lace Boot,Da...",I get so many compliments,This was a christmas gift i bought myself from...,0,1
20971,20972,real,5,Y,Shoes,B0099PG3VM,Eyekepper Small Size Stainless Steel Frame Spr...,Love these clip-ons,Love these clip-ons. They look better than th...,0,1
20972,20973,real,4,Y,Shoes,B0025KW3OY,"ACORN Women's Oh Ewe II Slipper,Walnut,8 M US",Mostly satisfied,"These are great slippers, very soft. The tag ...",0,1
20973,20974,real,3,Y,Shoes,B0069087NW,"Columbia Men's Newton Ridge Plus Hiking Boot,C...",Not waterproof,"It is a light, very comfortable boot, very che...",0,1
20974,20975,real,5,Y,Shoes,B003FQAV00,Salt Water Sandals by Hoy Shoe Original Sandal...,"Love these sandals for mama and baby, but pay ...",This is the second pair of these for my daught...,0,1
20975,20976,real,3,N,Shoes,B005HO2E2G,"Northside Men's Riverside II Open-Toe Sandal,B...",Looks better in pics than real,Cheaply made ofmilght weight plastics. but for...,0,0
20976,20977,real,5,Y,Shoes,B00IY7OSOU,"New Balance Women's WX813GR3 Training Shoe,Pin...",She says they are the most comfortable shoes s...,"I bought these for my daughter for gym class, ...",0,1
20977,20978,real,4,Y,Shoes,B00HHDCE02,"Gentle Souls Women's Bay Unique Rubber Flat,Mu...","Kinda Cute, Kinda Ugly!","Love them, although they are 'ugly, cute' shoe...",0,1
20978,20979,real,3,Y,Shoes,B00N7CSCPI,Sayoyo Baby Pink Tassels Soft Sole Leather Inf...,"Good price, guess this is the reason for the ...","Good price, guess this is the reason for the s...",0,1
20979,20980,real,5,Y,Shoes,B004JHQ0UE,Vera Bradley Small Cosmetic (Folkloric),Adorable......,"I have been looking for a Cosmetic bag, and I'...",0,1
20980,20981,real,5,Y,Shoes,B00IYAWBEQ,"Dr. Scholl's Women's Bellamy Western Boot,Blac...",These are literally my second favorite shoes. ...,These are literally my second favorite shoes. ...,0,1
20981,20982,real,5,Y,Shoes,B00APWMC90,"Vasque Women's Skadia Ultradry Snow Boot,Jet B...",Great boot,Got these just in time to hike on snow-covered...,0,1
20982,20983,real,2,Y,Shoes,B00IA6US7G,West Blvd Womens LIMA MOCCASIN Boots 3-Layer F...,Good thing they are only for one outfit to hav...,These run I would say two sizes smaller than w...,0,1
20983,20984,real,5,Y,Shoes,B00MI6FOFU,Journee Collection Womens Regular Sized and Wi...,I absolutely love these boots,I absolutely love these boots. I have large ca...,0,1
20984,20985,real,5,Y,Shoes,B0027EB42A,"The Professor Vintage Style Reading Glasses, 2...",Love the red glassees,"This is my second pair, great price, adorable ...",0,1
20985,20986,real,3,Y,Shoes,B006YUPGUO,"Funtasma Women's Saddle-48/B-W Platform Pump,B...",Oh my aching feet!,These shoes are absolutely adorable! But I hav...,0,1
20986,20987,real,5,Y,Shoes,B00H7ZL71C,Saucony Originals Women's Jazz Low Pro Sneaker...,Great for walking long distances or at work du...,Great for walking long distances or at work du...,0,1
20987,20988,real,5,Y,Shoes,B000GLP63O,"Ray-Ban 4075P Rectangular Wrap Sunglasses,Blac...",Fantastic and well worth the price!,It's tough to find a good pair of sunglasses. ...,0,1
20988,20989,real,5,Y,Shoes,B006NNZM92,TRG the One Shoe Cream 50ml #114 Light Gray,Good stuff,Revived a pair of Birkenstock Londons that I'd...,0,1
20989,20990,real,5,Y,Shoes,B00DJ87ZQ2,New Balance Men's ML574 Core Plus Fashion Snea...,Its the most comfortable shoe I never had before!,Its the most comfortable shoe I never had befo...,0,1
20990,20991,real,5,Y,Shoes,B00IAELO9O,"Skechers Womens Career-9 To 5 Flats Shoes,Blac...",Amazing,These shoes are absolutely amazing. They are t...,0,1
20991,20992,real,4,Y,Shoes,B00CY8PQUU,"Luichiny Women's Trend Lee Boot,Black,7 M US",AMAZING BOOTS / GREAT PRICE,These boots are an AMAZING alternative to the ...,0,1
20992,20993,real,1,Y,Shoes,B00AO3EELY,"Saucony Men's Hurricane 15 Running Shoe,White/...",It is too white!,"My son had ordered it but when it arrived, he ...",0,1
20993,20994,real,4,Y,Shoes,B004J2JPDI,"crocs Women's Neria Work Clog,Black,8 M US",Nice Shoe,These shoes fit well. I purchased to wear to ...,0,1
20994,20995,real,5,Y,Shoes,B006OYJW8W,Isotoner Women's Microterry PillowStep Satin C...,"These slippers are soft, warm, and very cozy ...","These slippers are soft, warm, and very cozy. ...",0,1
20995,20996,real,4,Y,Shoes,B00BXYM8T8,"Madden Girl Women's Gettaw Pump,Red Patent,7.5...",wide width is great!,"I bought these for work. I have high arches, ...",0,1
20996,20997,real,4,Y,Shoes,B0014C2ORK,"crocs Unisex Classic Clog,Khaki,6 US Men's / 8...",Love crocs!,Crocs are one of only two brands of shoes that...,0,1
20997,20998,real,5,Y,Shoes,B000EX8CCQ,Minnetonka Men's 703 Leather Laced Softsole Mo...,I love moccasins This fit like it was custom m...,I love moccasins This fit like it was custom ...,0,1
20998,20999,real,5,Y,Shoes,B00748YHVE,Ariat Womens Unbridled Fatbaby 9 B Powder Brown,"This fit well, comfortable, best investment",I wish these were a little more durable. I got...,0,1
20999,21000,real,4,Y,Shoes,B00A46KTLU,"VIBRAM FIVEFINGERS SPEED XC MENS HIKING SHOES,...","Love these shoes, except for the laces",I've been looking for a replacement for my bel...,0,1

### Question 1 - Correlation

In [3]:
data[['LABEL_INT', 'PRODUCT_CATEGORY']].groupby('PRODUCT_CATEGORY').agg(['sum', 'count', 'mean'])

                       LABEL_INT
                             sum count mean
PRODUCT_CATEGORY
Apparel                      350   700  0.5
Automotive                   350   700  0.5
Baby                         350   700  0.5
Beauty                       350   700  0.5
Books                        350   700  0.5
Camera                       350   700  0.5
Electronics                  350   700  0.5
Furniture                    350   700  0.5
Grocery                      350   700  0.5
Health & Personal Care       350   700  0.5
Home                         350   700  0.5
Home Entertainment           350   700  0.5
Home Improvement             350   700  0.5
Jewelry                      350   700  0.5
Kitchen                      350   700  0.5
Lawn and Garden              350   700  0.5
Luggage                      350   700  0.5
Musical Instruments          350   700  0.5
Office Products              350   700  0.5
Outdoors                     350   700  0.5
PC                           350   700  0.5
Pet Products                 350   700  0.5
Shoes                        350   700  0.5
Sports                       350   700  0.5
Tools                        350   700  0.5
Toys                         350   700  0.5
Video DVD                    350   700  0.5
Video Games                  350   700  0.5
Watches                      350   700  0.5
Wireless                     350   700  0.5

In [4]:
data['LABEL_INT'].corr(data['VERIFIED_PURCHASE_INT'])

-0.56981624262119279

In [5]:
data['LABEL_INT'].corr(data['RATING'])

-0.0097972205512207866

In [6]:
data[['LABEL_INT', 'RATING']].groupby('RATING').agg(['sum', 'count', 'mean'])

       LABEL_INT
             sum  count      mean
RATING
1            889   1757  0.505976
2            627   1192  0.526007
3            926   1868  0.495717
4           1999   3973  0.503146
5           6059  12210  0.496233

### Question 2 -

In [57]:
data['REVIEW_COUNT'] = data['REVIEW_TEXT'].str.count(r'\w+')

In [59]:
data[['LABEL', 'REVIEW_COUNT']].groupby('LABEL').agg(['count', 'mean', 'std'])

      REVIEW_COUNT
             count       mean         std
LABEL
fake         10500  61.050476   60.870686
real         10500  81.653810  109.870801

In [76]:
data['READABILITY'] = data['REVIEW_TEXT'].apply(textstat.flesch_reading_ease)

In [77]:
data[['LABEL', 'READABILITY']].groupby('LABEL').agg(['count', 'mean', 'std'])

      READABILITY
            count       mean        std
LABEL
fake        10500  79.759028  13.044638
real        10500  79.029707  13.187130

In [99]:
from nltk.corpus import stopwords

stopWords = set(stopwords.words('english'))

def count_stopwords(text):
    c = 0
    for word in text.split():
        if word in stopWords:
            c += 1
    return c

In [100]:
data['STOPWORDS_COUNT'] = data['REVIEW_TEXT'].apply(count_stopwords)

In [101]:
data[['LABEL', 'STOPWORDS_COUNT']].groupby('LABEL').agg(['count', 'mean', 'std'])

      STOPWORDS_COUNT
                count       mean        std
LABEL
fake            10500  24.696190  24.325351
real            10500  32.519048  43.813539

In [102]:
data['STOPWORDS_RATIO'] = data['STOPWORDS_COUNT'] / data['REVIEW_COUNT']

In [103]:
data[['LABEL', 'STOPWORDS_RATIO']].groupby('LABEL').agg(['count', 'mean', 'std'])

      STOPWORDS_RATIO
                count      mean       std
LABEL
fake            10500  0.401980  0.076370
real            10500  0.393652  0.077381

In [92]:
from string import punctuation

def count_punctuation(text):
    c = 0
    for word in text:
        if word in punctuation:
            c += 1
    return c

In [93]:
data['PUNCTUATION_COUNT'] = data['REVIEW_TEXT'].apply(count_punctuation)

In [94]:
data[['LABEL', 'PUNCTUATION_COUNT']].groupby('LABEL').agg(['count', 'mean', 'std'])

      PUNCTUATION_COUNT
                  count       mean        std
LABEL
fake              10500  10.182571  15.482145
real              10500  15.571524  25.888301

In [95]:
data['PUNCTUATION_RATIO'] = data['PUNCTUATION_COUNT'] / data['REVIEW_COUNT']

In [96]:
data[['LABEL', 'PUNCTUATION_RATIO']].groupby('LABEL').agg(['count', 'mean', 'std'])

      PUNCTUATION_RATIO
                  count      mean       std
LABEL
fake              10500  0.157543  0.091244
real              10500  0.178093  0.144681

In [109]:
def count_upper(text):
    return sum(1 for char in text if char.isupper())

In [110]:
data['UPPER_COUNT'] = data['REVIEW_TEXT'].apply(count_upper)
data[['LABEL', 'UPPER_COUNT']].groupby('LABEL').agg(['count', 'mean', 'std'])

      UPPER_COUNT
            count       mean        std
LABEL
fake        10500   8.712667  24.175636
real        10500  12.099905  27.639396

In [111]:
data['UPPER_RATIO'] = data['UPPER_COUNT'] / data['REVIEW_COUNT']
data[['LABEL', 'UPPER_RATIO']].groupby('LABEL').agg(['count', 'mean', 'std'])

      UPPER_RATIO
            count      mean       std
LABEL
fake        10500  0.136546  0.222843
real        10500  0.150311  0.262332

In [121]:
def name_in_text(row):
    text, title = row
    name_list = title.split()
    for name in name_list:
        if name in text:
            return 1
    return 0

In [124]:
data['IS_NAME_IN_TEXT'] = data[['REVIEW_TEXT', 'PRODUCT_TITLE']].apply(name_in_text, axis=1)
data[['LABEL', 'IS_NAME_IN_TEXT']].groupby('LABEL').agg(['count', 'mean', 'std'])

      IS_NAME_IN_TEXT
                count      mean       std
LABEL
fake            10500  0.456000  0.498084
real            10500  0.448381  0.497352

### Question 3 - Sentiment analysis

In [126]:
from textblob import TextBlob

In [127]:
def sentiment_score(text):
    tb = TextBlob(text)
    return tb.sentiment.polarity

In [129]:
data['SENTIMENT_SCORE'] = data['REVIEW_TEXT'].apply(sentiment_score)
data[['LABEL', 'SENTIMENT_SCORE']].groupby('LABEL').agg(['count', 'mean', 'std'])

      SENTIMENT_SCORE
                count      mean       std
LABEL
fake            10500  0.261757  0.234817
real            10500  0.233616  0.228647

#### my sentiment classifier is in ex1A_5+B_3